<!doctype html>
<html lang="en">
    <head>
        <title>Privacy Policy | Papa Gino's</title>
        <?php include('includes/meta.php'); ?>
        <?php include('includes/favicon.php'); ?>
        <?php include('includes/styles.php'); ?>
    </head>
    <body class="text-only">
        <?php include('includes/browserupgrade.php'); ?>
        <?php include('includes/header.php'); ?>
        <main>
            <section class="text-only__section">
                <div class="container">
                    <h1>Privacy Policy</h1>
                    <p><strong>Last Updated: November 19, 2018</strong></p>
                    <p>We value the trust you place in Papa Gino’s, Inc., including Papa Gino’s Pizzeria and D’Angelo Grilled Sandwiches (together “Papa Gino’s”) and we want you to be aware of the safeguards we have in place to respect your privacy. This Privacy Policy describes what information Papa Gino’s collects, how and why we collect it and how we strive to protect it.</p>
                    <p>This Privacy Policy applies only to information collected by Papa Gino’s when you use our Sites, including <a href="https://papaginos.com" target="_blank">www.papaginos.com</a> and <a href="https://dangelos.com" target="_blank">www.dangelos.com</a>, any of the Services or that you provide when you visit our retail locations or otherwise communicate or interact with Papa Gino’s.  For the purposes of this Privacy Policy, “you” or “your” shall refer to you as a User of the Sites. Capitalized terms used but not defined in this Privacy Policy will have the meanings ascribed to them in the Terms of Use, available <a href="terms.php">here</a> (the “Terms of Use”).</p>
                    <p>Before submitting information through the Sites or any of the Services, please review this Privacy Policy carefully. BY USING OR ACCESSING THE SITES OR ANY OF THE SERVICES, YOU ACKNOWLEDGE THAT YOU ACCEPT THE PRACTICES AND POLICIES DESCRIBED IN THIS PRIVACY POLICY. IF YOU DO NOT AGREE, PLEASE DO NOT USE OR ACCESS THE SITE OR ANY OF THE SERVICES.</p>
                    <p>If you prefer that we not collect any personal information from you, please do not provide us with any such information and limit your use of the Sites and Services. When you submit your personal information and other information to us, you consent to the collection, use and disclosure of such information as set forth in this Privacy Policy.</p>
                    <h2>How we collect information</h2>
                    <p>Papa Gino’s collects information from you in the following ways:</p>
                    <ul>
                        <li>Papa Gino’s collects information that you voluntarily provide when you use certain aspects of the Sites or the Services or when you visit one of our locations. Such information may include, without limitation, your name, phone number and/or e-mail.</li>
                        <li>When you use the Sites or the Services, technological tools, including, without limitation, “cookies,” collect certain information automatically, as explained in the following section.</li>
                    </ul>
                    <h2>What information we collect</h2>
                    <p>Papa Gino’s gathers Personal Information from you in order to provide superior service, customize our communications to you and administer our business. “Personal Information” is information that can personally identify you.</p>
                    <p><em>Information you Choose to Give Us.</em> If you choose to place an order, apply for a job, refer a potential employee, sign-up for our rewards program or text message program, or submit a site for a potential restaurant to us online, or otherwise interact with Papa Gino’s we may request certain Personal Information such as your name, residential and email addresses, and phone number. If you are interested in a franchise and would like to complete a franchise application online, we request not only your name, residential and email addresses and phone number but also your birthdate, social security number, immigration status, criminal history, and information regarding your assets and liabilities.</p>
                    <p>Providing your Personal Information to us is your choice. If you choose not to provide us with certain Personal Information, you may not be able to take advantage of all of the features of the Sites (including, without limitation, the Services).</p>
                    <p><em>E-mail.</em> In addition, when you send an email to us, we may retain your email address and the contents of the email you send.</p>
                    <p><em>Text Message Program.</em> By opting in to this program we retain your mobile number, double opt-in confirmation via your zip code reply, and carrier information. We might provide you with information about new products, program feature updates and special offers. <strong>You can opt out of text messages.</strong> If you’re subscribed to Papa Gino's, Inc. texting program and would like to opt out, call 1-844-788-7525.</p>
                    <p><em>Information Collected Automatically.</em> When you visit the Sites, we may automatically monitor your activity and collect general non-personal information, such as browser information, operating system information, search terms used to locate the Sites, IP address, the date, time and length of stay, specific web pages accessed by you during your visit to the Sites, the website that you go to when you leave the Sites and any downloading you performed while on the Sites.</p>
                    <p><em>Cookies and Tracking Technologies.</em> When ordering online or viewing the Sites, we may use tracking technology (“Cookies”) or similar technology to recognize your computer, store some information on your computer to, among other things, track what you order, and help make the Sites more user-friendly, efficient, and secure. Cookies should not harm your PC or contain any viruses. With most Internet browsers, you can erase the type of cookies we use from your computer hard drive, block our cookies, or receive a warning before our cookie is stored. We do not guarantee the effectiveness of browser cookie-blocking technologies, however.  Please note that while you may still use the Sites and the Services, your actions in connection with such functions will interfere with the Sites and the Services functioning properly. As a result, to make it easier to use the Sites, we recommend that your browser settings accept Cookies on the Sites.</p>
                    <p>We or our partners may also use Flash cookies (also known as Local Stored Objects) or other similar technologies. A Flash cookie is a small data file placed on a computer using Adobe Flash or similar technology that may be built into your computer or downloaded or installed by you to your computer. We use these technologies to personalize and enhance your online experience, facilitate processes, and personalize and store your settings.  They may be recognized by other sites or by our marketing or business partners. Flash cookies are different from browser cookies and the cookie management tools provided by your browser may not remove Flash cookies. Visit <a href="https://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager.html" target="_blank">www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager.html</a> to learn how to manage privacy and storage settings for Flash cookies. If you disable Flash cookies or other similar technologies, please be aware that you may not have access to certain features and services that make your online experience more efficient and enjoyable.</p>
                    <p>Papa Gino’s uses Google Analytics to monitor our Sites activity.  To learn how Google Analytics collects and processes data, please visit:  How Google uses data when you use our partners’ sites or apps” located at <a href="https://policies.google.com/technologies/partner-sites" target="_blank">www.google.com/policies/privacy/partners</a></p>
                    <p>If you access our mobile website or have downloaded our mobile app, we may also automatically collect information when you use our mobile website or download our mobile app about the type of mobile device you use, your mobile device identifier, your mobile operating system, pages you visit on our mobile websites, search terms, the type of mobile internet browsers you use and information about the way you use our mobile website and mobile applications.  Our mobile applications also may collect geo-location information, including from the GPS, Wi-Fi, or BlueTooth functions on your mobile device.  We may use this information in a variety of ways, including to determine which of our locations may be closest to you, whether you are within the allowed geographical ordering range of one of our locations, and to offer products and services to you.  You may be able to opt-out of sharing your geo-location information by changing the settings on your mobile device.  If you choose to opt-out, it may disable certain features of our mobile applications, including ordering.</p>
                    <h2>How we use the information we collect</h2>
                    <p>Except as specified in this Privacy Policy, Papa Gino’s does not rent, sell, trade or disclose your Personal Information to third parties without your consent. We use the information you provide to us only for the purpose for which it is requested. For example, when you place an order online, the information you provide will be used only to fill, bill and deliver your order to you at the address specified and, if necessary, to contact you about your order. The Personal Information you provide regarding your employment and your financial background, we use to evaluate your candidacy as either a potential employee or potential franchisee, depending upon the application you have submitted. Except as specified in this Privacy Policy, we do not sell or divulge your Personal Information to any third party, unless of course the law requires us to do so (as set forth below) or you have otherwise consented to such disclosure. We have established internal procedures to guarantee and ensure that the information you provide to us is used only for these purposes.</p>
                    <p>In addition, Papa Gino’s may use your Personal Information to:</p>
                    <ul>
                        <li>customize, analyze, adjust and improve the Sites and the Services to better meet your needs;</li>
                        <li>respond to your inquiries;</li>
                        <li>enforce Papa Gino’s user policies and other agreements with you;</li>
                        <li>provide you with important administrative information regarding the Sites and the Services, such as changes to this Privacy Policy, the Terms of Use or our other policies, and to, more generally, facilitate communication between Papa Gino’s and you; and</li>
                        <li>prevent fraud and other prohibited or illegal activities.</li>
                    </ul>
                    <p>In addition, Papa Gino’s may aggregate de-identified user data and information collected by Papa Gino’s in connection with your use of the Sites or the Services, with non-identifiable anonymous data from other users and customers to create anonymous aggregated data that does not identify you (“Aggregated Data”). Papa Gino’s shall solely own all rights in and to any Aggregated Data, and has the irrevocable right to maintain, store, use, disclose or sell such Aggregated Data. Papa Gino’s may use Aggregated Data for its internal purposes, including, without limitation, to perform statistical analyses, and for Papa Gino’s other legitimate business purposes.</p>
                    <h2>Disclosure of the information we collect</h2>
                    <p>We will not disclose your Personal Information without your consent, except as follows:</p>
                    <ul>
                        <li>We may retain other companies and individuals to perform functions on our behalf. Such third parties may be provided with access to Personal Information needed to perform their functions, in each case consistent with this Privacy Policy, but may not use such information for any other purpose.</li>
                        <li>We may disclose any information, including, without limitation, Personal Information, we deem necessary, in our sole discretion and without your prior permission, to comply with any applicable law, regulation, legal process or governmental request, or to protect the interests or safety of our visitors and customers, employees or others. This includes exchanging information with other companies and organizations for fraud protection and credit risk reduction. Papa Gino’s reserves the right to disclose your Personal Information if we believe you have or are violating this Privacy Policy or any other User policy available on the Sites, or in order to protect or defend Papa Gino’s rights or property, even without a subpoena, warrant or other court order. We may grant access to certain customer information (including Personal Information), subject to confidentiality restrictions, in connection with a sale, merger, liquidation, dissolution or insolvency proceeding involving a location, division or part or all of Papa Gino’s or its assets.</li>
                    </ul>
                    <p>Papa Gino’s does not assume, and expressly disclaims, any liability for third parties that have been provided with information as permitted by this Privacy Policy or who have collected information as permitted by this Privacy Policy (such as advertisers using third party cookies).</p>
                    <h2>Controlling your information</h2>
                    <p>We are committed to our customers and we respect their privacy. If you tell us that you do not want us to use your Personal Information to contact you, Papa Gino’s will respect your wishes. However, you acknowledge that, by opting-out of letting us use your Personal Information in accordance with this Privacy Policy, the Sites or certain Services, or features thereof, may no longer be available to you. In addition, we are not responsible for removing your Personal Information from the lists of any third party who has previously been provided your information in accordance with this Privacy Policy. If you would like to modify or delete your Personal Information (including, without limitation, your User Login, email address, contact information, other Personal Information and user preferences), please send an email to <a href="mailto:digitalmarketing@papaginos.com">DigitalMarketing@papaginos.com</a> with clear instructions about the information that you would like to have modified or deleted. You must promptly update your Personal Information if it changes or is inaccurate.</p>
                    <p>If you have been provided a User Login to access any Restricted Area, you are responsible for all actions taken with your User Login. Therefore, we recommend that you do not disclose such User Login to anyone. You may not allow others to use your User Login to access or use any part of the Sites or any Services. If your User Login has been compromised for any reason, you should contact us immediately to obtain a new User Login.</p>
                    <p>On your request, we will deactivate your User Login and remove your Personal Information from our active databases. We will retain in our files the Personal Information you have asked us to remove from our active databases to prevent fraud, resolve disputes, troubleshoot problems, assist with any investigations, enforce our User policies and comply with legal requirements. Therefore, you should not expect that your Personal Information will be completely removed from our databases in response to your requests. However, such Personal Information will only be available to select employees, service providers and governmental persons or entities.</p>
                    <h2>Opt-out policy</h2>
                    <p>You have the right to have any of the information you provide removed from our database at any time. To remove your information and/or terminate your registration, please email <a href="mailto:digitalmarketing@papaginos.com">DigitalMarketing@papaginos.com</a>. If you do not feel comfortable providing Personal Information via the Internet, you may do so by mail at the address provided below. However, we are not responsible for removing your Personal Information from the lists of any third party who has previously been provided your information in accordance with this Privacy Policy.</p>
                    <h2>Security</h2>
                    <p>Papa Gino’s has implemented appropriate and industry-standard data collection, storage and processing practices and security measures to protect against unauthorized access, alteration, disclosure or destruction of your personal information, username, password, transaction information and data stored on our Sites. While Papa Gino’s strives to protect your information, no data transmission over the Internet is 100% secure and, consequently, we cannot guarantee the security of any information, nor should you expect that your Personal Information, searches or other communications with Papa Gino’s will always remain secure. You should be aware that Papa Gino’s has no control over the security of other sites on the Internet that you might visit or interact with even when a link to any such third party site appears on our Sites.</p>
                    <p>In the event of a breach of the confidentiality or security of your Personal Information, Papa Gino’s will notify you as necessary so you can take appropriate protective steps. Papa Gino’s may notify you under such circumstances using the e-mail address(es) that we have on record for you.</p>
                    <h2>Children</h2>
                    <p>The Sites are general audience websites and do not target or intend to collect Personal Information from children. Papa Gino’s is concerned about the privacy and safety of children when they use the Internet. We will never knowingly request or collect Personal Information online from minors without prior verifiable parental consent.</p>
                    <p>To use any Sites or Service, you must be the age of legal majority in your place of residence. By using the Sites or any of the Services, you hereby represent that you are at least the age of legal majority in your place of residence or have otherwise provided us with parental consent. All information provided to Papa Gino’s will be treated as if it was provided by an adult, unless we have specific information to the contrary. If we discover that a child under 13 has provided us with Personal Information, we will take all reasonable measures to remove it from our systems immediately.</p>
                    <h2>Links to other websites</h2>
                    <p>Papa Gino’s may provide links on the Sites to third party websites that we do not own or control. Papa Gino’s assumes no responsibility for the information practices of websites you are able to access through the Sites. These links to other websites do not imply affiliation or endorsement of a linked site. Any access to and use of such linked websites is not governed by this Privacy Policy but, instead, is governed by the privacy policies of those third party websites. We encourage you to review and understand the terms of use and privacy practices of third party websites before providing any information to or through them.</p>
                    <h2>California residents</h2>
                    <p>If you are a resident of California, in addition to the rights set forth in this Privacy Policy, you have the right to request information from us regarding any disclosure of Personal Information to third parties for their direct marketing purposes. If you wish to make such a request, please send an e-mail to Papa Gino’s at <a href="mailto:digitalmarketing@papaginos.com">DigitalMarketing@papaginos.com</a>.</p>
                    <h2>Do not track</h2>
                    <p>Do Not Track (DNT) is a privacy preference that users can set in some web browsers, allowing users to opt out of tracking by websites and online services. At the present time, the World Wide Web Consortium (W3C) has not yet established universal standards for recognizable DNT signals and therefore, the Papa Gino’s Sites do not recognize DNT.</p>
                    <h2>United States of America</h2>
                    <p>The Sites are maintained in the United States of America. By using the Sites or any of the Services, you authorize the export of Personal Information to the United States of America and its storage and use by Papa Gino’s or its vendors, contractors and partners, anywhere in the world, as specified in this Privacy Policy.</p>
                    <h2>Privacy Policy changes</h2>
                    <p>Papa Gino’s reserves the right, in its discretion, to change, modify, add, or remove portions from this Privacy Policy at any time by posting such changes here. You should review this Privacy Policy regularly for changes, and can easily see if changes have been made by checking the Last Updated date above. However, if at any time in the future we plan to use Personal Information in a way that differs from this Privacy Policy, we will post such changes here and provide you the opportunity to opt-out of such differing uses. Your continued use following the posting of any changes to this Privacy Policy means you accept such changes. If you object to any such modification, your sole recourse is to stop using the Sites and/or the Services.</p>
                    <h2>How to contact us</h2>
                    <p>If you have any questions or concerns about this Privacy Policy, please contact us at:</p>
                    <p>Papa Gino’s, Inc.<br />
                    <a href="mailto:digitalmarketing@papaginos.com">Digital Marketing</a><br />
                    600 Providence Highway<br />
                    Dedham, MA 02026<br />
                    Email: DigitalMarketing@papaginos.com</p>
                </div>
            </section>
            <section class="mobile-order-btn">
                <a href="" target="_blank">Order Now!</a>
            </section>
        </main>
        <?php include('includes/footer.php'); ?>
        <?php include('includes/scripts.php'); ?>
    </body>
</html>