<!doctype html>
<html lang="en">
    <head>
        <title>Terms & Conditions | Papa Gino's</title>
        <?php include('includes/meta.php'); ?>
        <?php include('includes/favicon.php'); ?>
        <?php include('includes/styles.php'); ?>
    </head>
    <body class="text-only">
        <?php include('includes/browserupgrade.php'); ?>
        <?php include('includes/header.php'); ?>
        <main>
            <section class="text-only__section">
                <div class="container">
                    <h1>Terms & Conditions</h1>
                    <p><strong>Effective as of November 19, 2018<br />
                    PLEASE READ THE TERMS OF USE CAREFULLY.</strong></p>
                    <h2>1. ACKNOWLEDGEMENT AND ACCEPTANCE.</h2>
                    <p>a. These terms of use govern your use of Papa Gino’s, Inc.’s (“<strong>Site Operator</strong>”) online services (the “<strong>Services</strong>”) available through its web sites, <a href="https://papaginos.com" target="_blank">www.papaginos.com</a>, <a href="https://dangelos.com" target="_blank">www.dangelos.com</a>, <a href="https://orders.dangelos.com" target="_blank">https://orders.dangelos.com</a>, and its mobile and personal device applications (collectively, the “<strong>Applications</strong>” and together with such web site, collectively, the “Sites”, and each, a “Site”).</p>
                    <p>b. The Sites and the Services are owned and operated by the Site Operator and are provided under the following terms and conditions and any operating rules, policies, procedures and terms related to their use that may be published from time to time on a Site or otherwise provided to you by the Site Operator (collectively, the “<strong>Terms of Use</strong>”).</p>
                    <p>c. The Terms of Use govern your access to and use of the Services, including, without limitation, your access and use of the public areas of the Sites (“<strong>Public Areas</strong>”), as well as your access to and use of certain restricted areas and features of the Site (“<strong>Restricted Areas</strong>”). Unless otherwise indicated, the term “Site” as used throughout the Terms of Use shall include the Public Areas and the Restricted Areas. For the purposes of the Terms of Use, “you” or “your” shall refer to you as a User of a Site or any of the Services (“User”).</p>
                    <p>d. The Services are controlled and offered by Site Operator from its facilities in the United States of America. Site Operator makes no representations that any of the Sites or Services are appropriate or available for use in other jurisdictions. If you are a non-U.S. resident and you access any of the Sites or Services, you do so at your own risk and are responsible for compliance with local laws and regulations. You may not access, download, use or export any Site or Content (as defined below) or any Services in violation of U.S. export laws or regulations, or in violation of any other applicable laws or regulations.</p>
                    <p>e. <strong>PLEASE READ THESE TERMS OF USE CAREFULLY.</strong> BY ACCESSING AND USING ANY SITE OR SERVICE, YOU AGREE THAT YOU HAVE READ AND UNDERSTOOD AND AGREE TO BE BOUND BY THE TERMS OF USE, INCLUDING, WITHOUT LIMITATION, <a href="privacy.php">THE PRIVACY POLICY</a> POSTED ON OUR WEBSITE. YOU REPRESENT AND WARRANT THAT YOU HAVE THE AUTHORITY TO BIND THE USER TO THE TERMS OF USE. IF A USER IS NOT WILLING TO BE BOUND BY THE TERMS OF USE, DO NOT USE ANY SITE OR SERVICE. YOU REPRESENT TO US THAT YOU ARE EIGHTEEN (18) YEARS OF AGE OR OLDER. IF YOU ARE UNDER THE AGE OF 18, YOUR PARENT OR LEGAL GUARDIAN MUST AGREE TO THE TERMS OF USE ON YOUR BEHALF BEFORE YOU CAN USE ANY SITE OR SERVICE.</p>
                    <h2>2. LICENSE GRANT AND SITE CONTENT.</h2>
                    <p>a. Subject to the Terms of Use, Site Operator hereby grants you a nonexclusive, nontransferable right to access the Sites and the information, materials, data, text, graphics, images, sound files, animation files, video files and any other material or content made available through any Site or Service (collectively, the “<strong>Content</strong>”); provided, however, that only Registered Users (as defined below) have the right to access Restricted Areas and the Content therein and Services provided in connection therewith. Unauthorized access to any Service or to the telecommunications or computer facilities used to deliver any Service is a breach of the Terms of Use and is a violation of law.</p>
                    <p>b. You will protect the Content from unauthorized copying or use. Except as specifically permitted in the Terms of Use, you shall not, directly or indirectly, (i) transfer, sell, sublicense, rent or lease the Content; (ii) circumvent any encrypted data or gain access to more materials or data than was licensed or use any Site or Service in any manner which violates the Terms of Use or any applicable laws; (iii) reverse engineer, decompile, disassemble, translate or convert any computer programs used to access the Services (except as local law may permit without violation of local copyright law); or (iv) copy, reproduce, delete, disclose, distribute, display, perform, publish, adapt, create derivative works of, translate, or otherwise modify the Content, or permit any third party to engage in any of the acts proscribed in clauses (i) through (iv). You agree not to remove or alter any printed or on-screen copyright, trade secret or other legal notices contained on or in the Content. Reproduction of the Content in any form or by any means, including, but not limited to, information storage and retrieval systems, recordings and re-transmittals, use in any timesharing, service bureau, bulletin board or similar arrangement or public display without Site Operator’s written permission is forbidden. Any special rules for the use of certain Content or Services may be included elsewhere within a Site, otherwise provided to you by Site Operator, or contained in another written agreement between you and Site Operator, and are incorporated into the Terms of Use by reference.</p>
                    <p>c. The Content, the Sites and the Services are protected by copyright and other United States and foreign intellectual property and related laws. The Content provided by Site Operator may include both material owned or controlled by Site Operator and material owned or controlled by third parties and licensed to Site Operator. As between you and Site Operator, title to all Content, the Sites and the Services remains with Site Operator. Using, copying or storing any Content, Site or Service other than for noncommercial, personal use is expressly prohibited without prior written permission from Site Operator or the applicable copyright holder. All rights not expressly granted herein are reserved by Site Operator.</p>
                    <h2>3. RESTRICTED AREAS.</h2>
                    <p>A User may access the Restricted Areas by (a) providing certain information about such User (“<strong>Registration Data</strong>”) to Site Operator in order to set up an account for such User for access to Restricted Areas (each such User, a “<strong>Registered User</strong>”) and (b) through a combination of unique login credentials (collectively, “<strong>User ID</strong>”). Each Registered User is responsible for maintaining the confidentiality of his, her or its User ID. Furthermore, each Registered User is entirely responsible for any and all activities which occur under such User ID. Registered User agrees to immediately notify Site Operator of any unauthorized use of the Restricted Areas or a Registered User’s account or any other breach of security known to Registered User. Although Site Operator will not be liable for losses caused by any unauthorized use of Registered User’s account, Registered User may be liable for the losses of Site Operator or others due to such unauthorized use. Registered User is solely responsible for (a) any charges, damages, or losses that may be incurred or suffered as a result of Subscriber’s failure to maintain the strict confidentiality of the applicable User ID; and (b) promptly informing Site Operator in writing of any need to deactivate any User ID due to security concerns. Each Registered User must (i) maintain and update his or her Registration Data as required to keep information current, complete and accurate; (ii) provide all equipment, including, without limitation, a computer necessary to establish an Internet connection; (iii) provide for the Registered User’s own access to the Internet; and (iv) pay any fees associated with such access. Site Operator retains the right to terminate a Registered User’s rights to use the Restricted Areas or any Services provided in connection therewith (including, without limitation, by de-activating a Registered User’s User ID) upon notice to such Registered User if (x) any Registration Data provided by the Registered User is untrue, inaccurate, not current or incomplete, or if Site Operator has reasonable grounds to believe that any Registration Data is untrue, inaccurate, not current, or incomplete, or (y) Registered User otherwise breaches the Terms of Use. Upon termination of a Registered User’s rights to use the Restricted Areas, Registered User’s right to use the Restricted Areas shall immediately cease.</p>
                    <h2>4. PRIVACY POLICY.</h2>
                    <p>Registration Data and other information, including, without limitation, personally identifiable information, about Users will be treated in accordance with the <a href="privacy.php">Privacy Policy</a>. In addition to the restrictions on disclosure of Registration Data as set forth in the Privacy Policy, Site Operator will not disclose any personally identifiable information of a User unless authorized by that User or unless Site Operator is required to do so by law or in the good faith belief that such action is necessary to: (a) conform with applicable laws or comply with legal process; (b) protect and defend the rights or property of Site Operator or its licensors; or (c) enforce the Terms of Use.</p>
                    <h2>5. USER CONDUCT.</h2>
                    <p>You agree that when using any Site or Service, you will act in a manner consistent with the goals of such Site or Service, and by way of example, and not as a limitation, you specifically agree that you will not:</p>
                    <p>a. intentionally or unintentionally violate any applicable local, state, national or international laws or regulations;</p>
                    <p>b. use any spider, robot or other automated device or automated or manual process to copy, monitor, or keep a database copy of the Content or any portion of the applicable Site or Service</p>
                    <p>c. use such Site or Service to create any fraudulent or false inquiry or account;</p>
                    <p>d. transmit or post any abusive, threatening, unlawful, defamatory, libelous, false, misleading indications of origin or statements of fact, vulgar, obscene, indecent, sexually explicit, pornographic, profane or inflammatory material, or any material that could constitute or encourage conduct that would be considered a criminal offense, give rise to civil liability, or otherwise violate any law or for any other purpose that is unlawful or prohibited by the Terms of Use;</p>
                    <p>e. access or use such Site or Service in any way that, in Site Operator’s sole discretion, adversely affects the function or performance thereof or any other networks or computer systems used by Site Operator or any other Users, or infringes on Site Operator’s or any third party’s rights of privacy or publicity or any proprietary rights;</p>
                    <p>f. transmit or upload to any Site, or use in connection with such Service, any software, device or routine that contains viruses, worms, time bombs, Trojan horses or other computer programming routines that may interfere with or attempt to interfere with, damage or in any way intercept the normal operation of such Site or Service, or take any action that imposes an unreasonable load on the computing platform related thereto;</p>
                    <p>g. post information on or download information from a Site or Service unless you have all rights and authority necessary to do so;</p>
                    <p>h. falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material available through the use of such Site or Service;</p>
                    <p>i. attempt to “crack,” “hack,” “bomb,” manipulate or otherwise gain unauthorized access to other User accounts, Site Operator’s servers or software, or any areas of a Site not intended for your access;</p>
                    <p>j. post, transmit, or distribute any unsolicited advertising, promotional materials or other forms of solicitation to Users, individuals or entities, except in areas designated by Site Operator for such purposes</p>
                    <p>k. harvest, mine or otherwise collect or store personal information about other Users, including, without limitation, e-mail addresses and the content of User profiles; or</p>
                    <p>l. attempt to do any of the foregoing in this Section, or assist or permit any persons in engaging or attempting to engage in any of the activities described in this Section.</p>
                    <p>Violation of any of the above may, at any time without prior notice, result in a warning, temporary limit or suspension or immediate termination of your account or your access to the Sites or Services, reporting of your conduct to authorities, or legal action, as may be appropriate in the sole discretion of Site Operator. You acknowledge that Site Operator is not responsible for and does not assume any liability for Users’ acts or omissions in connection with the use of any Service, including, without limitation, with respect to the aforementioned activities. If you are or become aware of or experience any Content, activity or communication through or in connection with any Site or Service that appears to be in violation of the above, or in violation of any other provision of the Terms of Use, please inform Site Operator of any such violation by sending notification to <a href="mailto:digitalmarketing@papaginos.com">DigitalMarketing@papaginos.com</a>. If you believe your access to any Site or Service has been terminated in error, please contact us at <a href="mailto:digitalmarketing@papaginos.com">DigitalMarketing@papaginos.com</a>. Site Operator shall not have any liability to you or to any third party in respect of any limitation or suspension of your access to any Site or Service.</p>
                    <h2>6. COPYRIGHT NOTIFICATION.</h2>
                    <p>Site Operator does not permit copyright infringing activities and other infringement of intellectual property rights on any of its Sites, and Site Operator will remove Content if properly notified that such Content infringes on another's intellectual property rights. If you are a copyright owner or an agent thereof and believe that any Content in any area of a Site infringes upon or otherwise conflicts with your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act (“<strong>DMCA</strong>”) by providing Site Operator’s designated Copyright Agent with the following information in writing (see 17 U.S.C. § 512(c)(3) for further detail):</p>
                    <p>a. a physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed</p>
                    <p>b. identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site;</p>
                    <p>c. identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled and information reasonably sufficient to permit the service provider to locate the material;</p>
                    <p>d. information reasonably sufficient to permit the service provider to contact you, such as an address, telephone number and an electronic mail address;</p>
                    <p>e. a statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</p>
                    <p>f. a statement that the information in the notification is accurate and, under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</p>
                    <p>Please contact Site Operator’s designated Copyright Agent at <a href="mailto:digitalmarketing@papaginos.com">DigitalMarketing@papaginos.com</a> to send notifications of claimed infringement. You hereby acknowledge and agree that if you fail to comply with all of the requirements listed above, your DMCA notice may not be valid.</p>
                    <h2>7. TRADEMARKS.</h2>
                    <p>Papa Gino’s, Papa Gino’s Pizzeria, D’Angelos Grilled Sandwiches, the Sites’ logos, and other product and service names of Site Operator are trademarks of Site Operator (collectively, the “<strong>Marks</strong>”). You agree not to display, reproduce or otherwise use in any manner the Marks without Site Operator’s prior written permission.</p>
                    <h2>8. LINKS.</h2>
                    <p>The Sites may provide links to other web sites or resources. Site Operator is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any content, advertising, products or other materials on or available from such sites or resources. Site Operator shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, products or services available on such external sites or resources. Site Operator provides these links and references to you only as a convenience. Unless otherwise expressly stated, a link does not imply Site Operator’s endorsement, sponsorship or recommendation of, or affiliation with, the linked site or its content, and Site Operator does not accept any responsibility therefore.  You should carefully review the applicable terms and privacy policy of any such website before use.</p>
                    <h2>9. CONFIDENTIAL INFORMATION.</h2>
                    <p>Content that is provided to or accessible through the Restricted Areas may include confidential information of Site Operator. Registered Users may only use such confidential information in accordance with the Terms of Use. Registered User is responsible for all unauthorized uses or disclosures of Site Operator’s confidential information by Registered User or any other entity to whom Registered User discloses such confidential information. Registered User agrees that any actual or threatened breach of this Section 9 would cause irreparable harm to Site Operator, that money damages will not provide an adequate remedy and that Site Operator is entitled to seek an injunction or other equitable relief in addition to any other remedy or recourse available to Site Operator under the Terms of Use, at law or in equity, and Registered User waives the posting of any bond or surety.</p>
                    <h2>10. DISCLAIMER OF WARRANTIES.</h2>
                    <p>a. THE USE OF ANY OF THE SITES OR SERVICES IS AT THE USER’S SOLE RISK. EACH OF THE SITES AND SERVICES IS PROVIDED ON AN “AS IS” “AS AVAILABLE” BASIS. SITE OPERATOR DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT, QUIET ENJOYMENT, ACCURACY, INTEGRATION, COMPLETENESS OR RELIABILITY OF THE CONTENT, THE AVAILABILITY OF THE SITES OR ANY SERVICES AT ANY PARTICULAR TIME OR LOCATION, THE CORRECTION OF ANY DEFECTS OR ERRORS IN THE SITES OR THE SERVICES, OR THAT CONTENT IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, AS WELL AS ALL WARRANTIES ARISING BY USAGE OF TRADE, COURSE OF DEALING OR COURSE OF PERFORMANCE. SITE OPERATOR MAKES NO WARRANTY THAT ANY OF THE SITES OR THE SERVICES WILL MEET THE USER’S REQUIREMENTS OR THAT USE OF SUCH SITES OR SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR FREE, NOR DOES SITE OPERATOR MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE THEREOF.</p>
                    <p>b. ANY MATERIAL OR DATA DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF ANY SITE OR SERVICE IS DONE AT THE USER’S OWN DISCRETION AND RISK, AND THE USER WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO THE USER’S COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OR USE OF SUCH MATERIAL OR DATA. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY THE USER FROM SITE OPERATOR OR THROUGH ANY OF THE SITES OR SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.</p>
                    <p>c. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES. ACCORDINGLY, SOME OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO USERS.</p>
                    <h2>11. LIMITATION OF LIABILITY.</h2>
                    <p>a. UNDER NO CIRCUMSTANCES SHALL SITE OPERATOR, ITS DIRECTORS, OFFICERS, EMPLOYEES, AGENTS OR OTHER REPRESENTATIVES BE LIABLE TO THE USER OR TO ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, SPECIAL, CONSEQUENTIAL (INCLUDING, WITHOUT LIMITATION, LOSS OF PROFITS, LOSS OF USE, TRANSACTION LOSSES, OPPORTUNITY COSTS, INTERRUPTION OF BUSINESS OR COSTS OF PROCURING SUBSTITUTE GOODS), OR ANY OTHER DAMAGES OF ANY KIND, RESULTING FROM, ARISING OUT OF OR IN ANY WAY RELATING TO THE USE OR THE INABILITY TO USE ANY OF THE SITES OR SERVICES, UNAUTHORIZED ACCESS TO, DELETION OR ALTERATION OF THE USER’S DATA, OR FAILURE TO STORE THE USER’S DATA, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, USE, DATA OR OTHER INTANGIBLE PROPERTY, EVEN IF SITE OPERATOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
                    <p>b. IN EACH CASE, THE FOREGOING LIMITATIONS AND EXCLUSIONS ARE INTENDED TO APPLY REGARDLESS OF THE FORM OF THE CLAIM OR ACTION, WHETHER BASED ON CONTRACT (INCLUDING FUNDAMENTAL BREACH), TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, STATUTORY OR OTHERWISE, AND REGARDLESS OF WHETHER OR NOT SUCH DAMAGES WERE FORESEEN, UNFORESEEN OR FORESEEABLE. EACH PARTY ACKNOWLEDGES AND AGREES THAT THE LIMITATIONS OF LIABILITY SET FORTH ABOVE ARE A CONDITION OF THE OTHER PARTY ENTERING INTO THE TERMS OF USE.</p>
                    <p>c. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO THE USER.</p>
                    <h2>12. INDEMNIFICATION.</h2>
                    <p>You agree to indemnify, defend and hold harmless Site Operator and its affiliates, directors, officers, employees and agents, from any claim, demand, liability, expense or loss, including reasonable attorneys’ fees and costs, due to or arising out of, or in any way connected with your use of or access to any Site or Service or the Content, your violation of any part of the Terms of Use, or your use, or the use by any other person, of your User ID. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you (and without limiting your indemnification obligations with respect to such matter), and in such case, you agree to cooperate with our defense of such claim.</p>
                    <h2>13. USER FEEDBACK.</h2>
                    <p>Site Operator is pleased to hear from Users and welcomes your comments regarding the Sites and the Services. If you send Site Operator your feedback, ideas and materials (collectively, “Feedback”), please understand that by submitting such Feedback to Site Operator, you irrevocably assign to Site Operator, free of charge, all worldwide rights, title and interest in all copyrights and other intellectual property rights in such Feedback. Site Operator will be entitled to use such Feedback for any purpose whatsoever without restriction and without compensating you in any way, and by submitting Feedback, you represent to Site Operator that you have the right to do so.</p>
                    <h2>14. MODIFICATION, WAIVERS, INTEGRATION.</h2>
                    <p>Site Operator may modify, add or remove any portion of the Terms of Use at any time and from time to time. Notification of such changes to the Terms of Use will be posted on the Sites and will be effective immediately thereafter. Your continued use of a Site or Service covered by such Terms of Use after the posting of the modified Terms of Use constitutes your agreement to abide and be bound by such terms, as modified. Should you object to any modification, your sole recourse is to terminate your use thereof. The Terms of Use may not otherwise be modified, except in a writing signed by both parties. Site Operator reserves the right to modify or discontinue any Site or Service (or any portion thereof), temporarily or permanently, with or without notice to you, and is not obligated to support or update the Sites. Site Operator shall not be liable to you or any third party in the event that Site Operator exercises its right to modify or discontinue a Site (or any portion thereof). Unless explicitly stated otherwise, any new features that augment or enhance a Site shall be subject to the Terms of Use. No delay or failure on the part of either party in exercising any right or remedy hereunder shall operate as a waiver thereof or of any other right or remedy. No waiver whatsoever shall be valid unless in writing, signed by the party to be charged, and then only to the extent therein set forth. The Terms of Use constitute the entire agreement of the parties with respect to the matters contemplated hereby.</p>
                    <h2>15. NOTICES.</h2>
                    <p>Any notice or other communication required or permitted to be made under the Terms of Use may be delivered in person, by facsimile, by United States certified or registered mail, by a nationally-recognized overnight courier or, as provided below, by electronic means. Except as otherwise provided herein, a notice shall be effective (a) upon receipt, if delivered in person; (b) upon receipt (confirmed by automatic answer back or like evidence of receipt), if sent by facsimile during normal business hours at the office of the recipient thereof and otherwise at the opening of business at such recipient’s office on the next business day; (c) three (3) days after deposit into the United States mail, if sent by certified or registered mail, return receipt requested; (d) at 11:00 a.m. on the next business day, if sent by overnight courier; and (e) as provided below, if sent by electronic means. In each case, such notice to any party shall be made to the mailing or e-mail address of such party indicated (i) in the case of Site Operator, below, (ii) in the case of a Registered User, in the Registration Data, or (iii) in the case of any other User, to the last e-mail address provided by such User, if any (and in the absence thereof, notice will be valid if made in accordance with the last sentence of this Section 15). Either party may from time to time change its address for receiving notices in writing, or its electronic address, by posting a change of address on the Site or by sending a notice to the other party in writing or by electronic means promptly confirmed in writing. Any notice or other communication to be made hereunder, even if otherwise required to be in writing under other provisions of the Terms of Use, may alternatively be made electronically to the electronic addresses set forth (1) in the case of Site Operator, below, (2) in the case of a Registered User, to the e-mail address or other contact information included in the Registration Data, or (3) in the case of any other User, to the e-mail address or other contact information last provided to Site Operator by such User (if any). Any notice or other communication made in electronic form will have the same legal effect and enforceability as if made in non-electronic form. Site Operator may also broadcast notices or messages on the Sites and such broadcasts shall constitute notice to Users.</p>
                    <p>16. ASSIGNMENT, SEVERABILITY AND THIRD PARTIES.<br />
                    You shall not assign or otherwise transfer the Terms of Use, in whole or in part, or delegate or subcontract any of its rights or obligations hereunder, without Site Operator’s prior written consent. Any attempted transfer or delegation by you without Site Operator’s consent will be void. The Terms of Use will bind and inure to the benefit of each party's successors and permitted assigns. The invalidity or unenforceability of any one or more sections of the Terms of Use shall not affect the validity or enforceability of its remaining provisions. The Terms of Use shall confer no rights upon any other party other than the parties hereto.</p>
                    <h2>17. GOVERNING LAW AND JURISDICTION.</h2>
                    <p>All matters arising from or relating to the use and operation of the Site will be governed by and interpreted in accordance with laws of the Commonwealth of Massachusetts, without reference to principles of conflicts of law. The parties hereto hereby consent to the non-exclusive jurisdiction of any local, state or federal court located within the Commonwealth of Massachusetts. The parties waive personal service of any and all process and agree that all such service of process may be made by certified or registered mail, return receipt requested, directed to such party, at the address indicated in Section 15. TO THE EXTENT PERMITTED BY LAW, EACH OF THE PARTIES HERETO HEREBY WAIVES ITS RIGHT TO TRIAL BY JURY IN ANY SUIT OR PROCEEDING ARISING UNDER OR RELATING TO THE TERMS OF USE.</p>
                    <h2>18. TERMINATION</h2>
                    <p>We may suspend or terminate your account or use of the Sites at any time, for any reason or for no reason.  You are personally liable for any orders placed or charges incurred through your account prior to termination.  We reserve the right to change, suspend, or discontinue all or any aspect of the Sites at any time without notice.</p>
                    <h2>19. ACKNOWLEDGMENT.</h2>
                    <p>You acknowledge that You have read and understand the Terms of Use, and that the Terms of Use have the same force and effect as a signed agreement.</p>
                    <h2>20. CONTACTING US</h2>
                    <p>If you have any questions about the Terms and Conditions, please call us at 781-467-1600, e-mail us at <a href="digitalmarketing@papaginos.com">DigitalMarketing@papaginos.com</a> or write to us at the following address:</p>
                    <p>Papa Gino’s, Inc.<br />
                    600 Providence Highway<br />
                    Dedham, MA 02026</p>
                    <h2>21. TEXT MESSAGING (“SMS”) TERMS OF USE</h2>
                    <p>IMPORTANT: THESE TEXT MESSAGING TERMS OF USE APPLY ONLY IF YOU HAVE OPTED TO RECEIVE TEXT MESSAGES FROM PAPA GINO'S, INC. on behalf of Papa Gino's or D'Angelo restaurants, (“we” or “us”).</p>
                    <p>When you opt in to our SMS program, you understand and agree that the Website Terms of Use are incorporated into, and become part of, the SMS Terms of Use (and both documents are together, the “Terms”). THE TERMS CONTAIN AN ARBITRATION AGREEMENT, JURY AND CLASS ACTION WAIVERS, LIMITATIONS ON OUR LIABILITY, AND OTHER PROVISIONS THAT AFFECT YOUR LEGAL RIGHTS REGARDING THE SMS PROGRAM.  PLEASE CAREFULLY READ AND UNDERSTAND THESE TERMS.</p>
                    <p>1. SMS offers are only accessible on smartphone devices and we may change the SMS opt-in offer without notice.  If you have opted in to receive text messages we do not charge you for the text message.  Standard messaging and data rates will apply to each text message received as provided for in the wireless plan with your carrier.  If you have entered your mobile # and your zip code and clicked “REGISTER” on our website then you have agreed to receive up periodic autodialed ads and other marketing messages per month from us on your mobile #.  We do not require you to agree to receive text messages as a condition of making any purchase.  If you need help with text messages text HELP to 40518. Currently, AT&T, Verizon Wireless, Sprint, Virgin, T-Mobile, US Cellular, Cricket (Leap), MetroPCS, C Spire, Carolina West Wireless (CWW), CellCom, and Bandwidth are participating carriers but these may change without notice.  SMS may not be delivered to you if your phone is not in the range of a transmission site, or if sufficient network capacity is not available at a particular time.  Even within coverage, factors beyond the control of the participating carriers Verizon and T-Mobile/MetroPCS may interfere with messages delivery for which the carrier is not responsible.  T-Mobile/Metro PCS does not guarantee that SMS will be delivered.  If you wish to opt out of receiving text messages from us text STOP to 40518 or call (844) 788-7525.  If you opt out, you will receive 1 final text message confirming your decision to unsubscribe.</p>
                    <p>2. Several of our D'Angelo restaurants are owned and operated by franchisees. These terms do not apply to any of our franchisees’ text marketing programs that are not using short code 40518. If you are receiving text messages from a D'Angelo franchisee on a different short code, you will need to opt out from them directly. Each franchisee is solely and independently responsible for its legal and regulatory compliance.</p>
                </div>
            </section>
            <section class="mobile-order-btn">
                <a href="" target="_blank">Order Now!</a>
            </section>
        </main>
        <?php include('includes/footer.php'); ?>
        <?php include('includes/scripts.php'); ?>
    </body>
</html>